I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 72, in script call
    call tutor_7 from _call_tutor_7
  File "game/script.rpy", line 391, in script
    show image code_23 at truecenter
  File "game/script.rpy", line 391, in <module>
    show image code_23 at truecenter
NameError: name 'code_23' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 72, in script call
    call tutor_7 from _call_tutor_7
  File "game/script.rpy", line 391, in script
    show image code_23 at truecenter
  File "C:\ProgramData\chocolatey\lib\renpy\tools\renpy-7.3.5-sdk\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\ProgramData\chocolatey\lib\renpy\tools\renpy-7.3.5-sdk\renpy\ast.py", line 1384, in show_imspec
    expression = renpy.python.py_eval(expression)
  File "C:\ProgramData\chocolatey\lib\renpy\tools\renpy-7.3.5-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\ProgramData\chocolatey\lib\renpy\tools\renpy-7.3.5-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 391, in <module>
    show image code_23 at truecenter
NameError: name 'code_23' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
renpy_game 1.0
Mon Nov 27 18:56:03 2023
